'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FRMPanneauDeControle

	'''<summary>
	'''Head1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

	'''<summary>
	'''form1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''tsmTest control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tsmTest As Global.AjaxControlToolkit.ToolkitScriptManager

	'''<summary>
	'''imgbtnLogo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imgbtnLogo As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''Label1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''Label2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lnkConnexion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkConnexion As Global.System.Web.UI.HtmlControls.HtmlAnchor

	'''<summary>
	'''Label3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lnkAnglais control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkAnglais As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''iconSetting control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents iconSetting As Global.System.Web.UI.HtmlControls.HtmlAnchor

	'''<summary>
	'''divLogin control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divLogin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''lblInfoUtilisateur control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblInfoUtilisateur As Global.System.Web.UI.HtmlControls.HtmlAnchor

	'''<summary>
	'''lblPipeLogin control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblPipeLogin As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lnkbtnLogout control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkbtnLogout As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblTitreConfig control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTitreConfig As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''imgBtn_EnvoiMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imgBtn_EnvoiMessage As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lnkButton_accueil control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkButton_accueil As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkButton_nouvelle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkButton_nouvelle As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkButton_evenement control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkButton_evenement As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkButton_revueDePresse control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkButton_revueDePresse As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkButton_utilisateur control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkButton_utilisateur As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''MultiView control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents MultiView As Global.System.Web.UI.WebControls.MultiView

	'''<summary>
	'''viewOptions control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents viewOptions As Global.System.Web.UI.WebControls.View

	'''<summary>
	'''lblMessageErreurOptions control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMessageErreurOptions As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lviewOptions control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lviewOptions As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''ViewNouvelle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewNouvelle As Global.System.Web.UI.WebControls.View

	'''<summary>
	'''lviewNouvelle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lviewNouvelle As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''lblMessageErreurNouvelle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMessageErreurNouvelle As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lviewInfoNouvelles control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lviewInfoNouvelles As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''ViewEvenement control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewEvenement As Global.System.Web.UI.WebControls.View

	'''<summary>
	'''lvEvenement control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lvEvenement As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''lblMessageErreurEvenement control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMessageErreurEvenement As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lvInfoEvenement control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lvInfoEvenement As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''ViewRevueDePresse control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewRevueDePresse As Global.System.Web.UI.WebControls.View

	'''<summary>
	'''lvRDP control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lvRDP As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''lblMessageErreurRDP control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMessageErreurRDP As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lvInfoRDP control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lvInfoRDP As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''ViewUtilisateur control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewUtilisateur As Global.System.Web.UI.WebControls.View

	'''<summary>
	'''lviewUtilisateurs control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lviewUtilisateurs As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''lblMessageErreurInfoUtilisateur control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMessageErreurInfoUtilisateur As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lviewInfoUtilisateur control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lviewInfoUtilisateur As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''viewMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents viewMessage As Global.System.Web.UI.WebControls.View

	'''<summary>
	'''Label11 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblMessageErreurEnvoiMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMessageErreurEnvoiMessage As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTitreMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTitreMessage As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtboxTitreMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtboxTitreMessage As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtboxMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtboxMessage As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''htmleditorMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents htmleditorMessage As Global.AjaxControlToolkit.HtmlEditorExtender

	'''<summary>
	'''lnkbtnEnvoiMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkbtnEnvoiMessage As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''LnkBtnNavigation_footer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LnkBtnNavigation_footer As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''LnkBtnHistorique_footer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LnkBtnHistorique_footer As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''LnkBtnNouvelles_footer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LnkBtnNouvelles_footer As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''LnkBtnEvenement_footer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LnkBtnEvenement_footer As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''LnkBtnRDP_footer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LnkBtnRDP_footer As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''LnkBtnDevenirSentinelle_footer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LnkBtnDevenirSentinelle_footer As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''LnkBtnInfoSuicide_footer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LnkBtnInfoSuicide_footer As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''LnkBtnInfoMaltraitance_footer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LnkBtnInfoMaltraitance_footer As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''LnkBtnZoneSentinelle_footer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LnkBtnZoneSentinelle_footer As Global.System.Web.UI.WebControls.LinkButton
End Class
