'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class index

	'''<summary>
	'''lblPenseeAccueil control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblPenseeAccueil As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lvPremiereNouvellesAccueil control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lvPremiereNouvellesAccueil As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''lvNouvellesAccueil control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lvNouvellesAccueil As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''lvPremierEvenementAccueil control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lvPremierEvenementAccueil As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''lvEvenementAccueil control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lvEvenementAccueil As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''lvPremiereRDPAccueil control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lvPremiereRDPAccueil As Global.System.Web.UI.WebControls.ListView

	'''<summary>
	'''lvRDPAccueil control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lvRDPAccueil As Global.System.Web.UI.WebControls.ListView
End Class
