'Classe qui est hérité de tous les formulaires et qui sert au traitement d'erreur au niveau
'de la page

Imports System.Threading
Public Class FRMdeBase
    Inherits System.Web.UI.Page

    'Méthode hérité par toute les pages servant à gérer les erreurs au niveau de la page
    Private Sub Page_Error(ByVal sender As Object, ByVal e As EventArgs) Handles Me.Error
        ' Get last error from the server
        Dim exc As Exception = Server.GetLastError

        ' Handle exceptions generated by Button 1
        If TypeOf exc Is InvalidOperationException Or TypeOf exc Is ArgumentOutOfRangeException Then
            ' Pass the error on to the Generic Error page
            Server.Transfer("FRMPageErreur.aspx?handler=Page_Error%20-%FRMdeBase.vb", True)
            ExceptionUtility.LogException(exc, "FRMdeBase")
            Server.ClearError()
        End If
    End Sub
End Class
