'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InfoGenerale
    Public Property idInfo As Integer
    Public Property penseeFR As String
    Public Property penseeEN As String
    Public Property temoignageFR As String
    Public Property temoignageEN As String
    Public Property courrielFormulaire As String
    Public Property idUtilisateur As Nullable(Of Integer)
    Public Property historiqueFR As String
    Public Property historiqueEN As String
    Public Property maltraitanceFR As String
    Public Property maltraitanceEN As String

    Public Overridable Property Utilisateur As Utilisateur

End Class
