'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class model_sentinelleshyContainer
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=model_sentinelleshyContainer")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property ÉvénementJeu() As DbSet(Of Événement)
    Public Property NouvelleJeu() As DbSet(Of Nouvelle)
    Public Property RevueDePresseJeu() As DbSet(Of RevueDePresse)
    Public Property StatutJeu() As DbSet(Of Statut)
    Public Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Property UtilisateurJeu() As DbSet(Of Utilisateur)
    Public Property InfoGeneraleJeu() As DbSet(Of InfoGenerale)
    Public Property CategorieJeu() As DbSet(Of Categorie)
    Public Property PublicationJeu() As DbSet(Of Publication)

End Class
