'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Nouvelle
    Public Property idNouvelle As Integer
    Public Property titreFR As String
    Public Property contenuFR As String
    Public Property titreEN As String
    Public Property contenuEN As String
    Public Property dateRedaction As Date
    Public Property idUtilisateur As Nullable(Of Integer)

End Class
