'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Statut
    Public Property nomStatutFR As String
    Public Property nomStatutEN As String
    Public Property idStatut As Integer

    Public Overridable Property Utilisateur As ICollection(Of Utilisateur) = New HashSet(Of Utilisateur)

End Class
