'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class sysdiagrams
    Public Property name As String
    Public Property principal_id As Integer
    Public Property diagram_id As Integer
    Public Property version As Nullable(Of Integer)
    Public Property definition As Byte()

End Class
