'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Utilisateur
    Public Property nomUtilisateur As String
    Public Property motDePasse As String
    Public Property SelDeMer As String
    Public Property UrlAvatar As String
    Public Property dateInscription As Date
    Public Property courriel As String
    Public Property milieu As String
    Public Property nom As String
    Public Property prenom As String
    Public Property sexe As String
    Public Property noTelephone As String
    Public Property idUtilisateur As Integer
    Public Property idStatut As Nullable(Of Integer)

    Public Overridable Property Événement As ICollection(Of Événement) = New HashSet(Of Événement)
    Public Overridable Property RevueDePresse As ICollection(Of RevueDePresse) = New HashSet(Of RevueDePresse)
    Public Overridable Property Statut As Statut
    Public Overridable Property InfoGenerale As ICollection(Of InfoGenerale) = New HashSet(Of InfoGenerale)
    Public Overridable Property PublicationJeu As ICollection(Of Publication) = New HashSet(Of Publication)

End Class
